import { execSync } from "child_process"
import { cli } from "../src/app"
import { readFileSync } from "fs"
import {
  ttDir,
  cliArgs as args,
  dev_ttDir,
  noop,
  production,
  ttFiles,
} from "../src/util"
import rm from "rimraf"

const testDir = `${dev_ttDir}-cli.test`

afterAll(() => {
  execSync(`mkdir -p ${testDir}`)
  ttFiles.forEach((file) => {
    execSync(`echo { "autoGenerated": 0 } > ${testDir}/${file}`)
  })
})

describe("cli test", () => {
  test("tt init creates .tt and files with default {} data", () => {
    rm.sync(testDir)
    cli(args("init"), { ttRoot: testDir })

    ttFiles.forEach((file) => {
      const result = readFileSync(`${testDir}/${file}`, "utf-8")
      const parsed = JSON.parse(result)
      const expected = {}
      expect(parsed).toEqual(expected)
    })
  })
})
