import { execSync } from 'child_process'
import { cli } from '../src/app'
import { writeFileSync } from 'fs'
import {
  cliArgs,
  dev_ttDir,
  ttFiles,
  stateFile,
  historyFile,
  defaultTask,
} from '../src/util'

const testDir = `${dev_ttDir}-mode_log.test`
const testState = `${testDir}/${stateFile}`
const testHistory = `${testDir}/${historyFile}`

beforeAll(() => {
  execSync(`mkdir -p ${testDir}`)
  const testJSON = { autoGenerated: 0 }

  ttFiles.forEach(file => {
    writeFileSync(`${testDir}/${file}`, JSON.stringify(testJSON))
  })
})

describe('tt log', () => {
  test('`tt log last`', () => {
    const mock = jest.fn()
    const expected = 'foo'
    process.stdout.write = mock
    cli(cliArgs('log', 'last'), { ttRoot: testDir })

    expect(mock).toHaveBeenCalledWith(expected)
  })
})
