import { execSync } from "child_process"
import { cli } from "../src/app"
import { readFileSync, writeFileSync } from "fs"
import {
  ttDir,
  cliArgs,
  dev_ttDir,
  noop,
  production,
  ttFiles,
  stateFile,
  historyFile,
} from "../src/util"
import rm from "rimraf"
import { State } from "../src/core"

const testDir = `${dev_ttDir}-mode_stop.test`
const testState = `${testDir}/${stateFile}`
const testHistory = `${testDir}/${historyFile}`

beforeAll(() => {
  execSync(`mkdir -p ${testDir}`)
  const testJSON = { autoGenerated: 0 }

  ttFiles.forEach(file => {
    // console.log(`${testDir}/${file}`)
    writeFileSync(`${testDir}/${file}`, JSON.stringify(testJSON))
  })
})

describe("tt stop", () => {
  test("`tt new, tt stop`", () => {
    cli(cliArgs("new"), { ttRoot: testDir })
    cli(cliArgs("stop"), { ttRoot: testDir })

    const result = readFileSync(testState, "utf-8")
    const parsed: State = JSON.parse(result)
    const expected: State["task"] = {
      name: expect.any(String),
      sprints: [
        {
          start: expect.any(Number),
        },
      ],
    }
    expect(parsed.task).toEqual(expected)
  })
})
