import { cli } from './src/app'
import { cliArgs, dev_ttDir, ttFiles } from './src/util'
import { writeFileSync, mkdirSync } from 'fs'

const testDir = `${dev_ttDir}-mode_log.test`
const testJSON = { autoGenerated: 0 }

mkdirSync(testDir, { recursive: true })
ttFiles.forEach(file => {
  writeFileSync(`${testDir}/${file}`, JSON.stringify(testJSON))
})

cli(cliArgs('new', 'study'), { ttRoot: testDir })
cli(cliArgs('stop'), { ttRoot: testDir })
console.log('here lol\n\n\n\n\n')
cli(cliArgs('log', 'last'), { ttRoot: testDir })
